#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build json schemas for per-collection queryables
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Building queryables..."

    docker-compose \
        -f docker-compose.yml \
        -f docker-compose.dev.yml \
        run --rm \
        stac-dev python /opt/src/scripts/bin/build_queryables.py

    echo "Done."

fi
