#!/bin/bash

source scripts/env

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") --acr ACR_NAME --tag IMAGE_TAG
Publishes images for this project.

Must be logged in to the ACR (e.g. with az acr login -n ACR_NAME)

--acr: The name of the ACR to publish to
"
}

while [[ "$#" > 0 ]]; do case $1 in
    --acr)
        ACR_NAME=$2
        shift
        shift
        ;;
    --tag)
        IMAGE_TAG=$2
        shift
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac done

if [[ -z ${ACR_NAME} ]]; then
    echo "Must pass in ACR_NAME with --acr"
    exit 1
fi

if [[ -z ${IMAGE_TAG} ]]; then
    echo "Must pass in IMAGE_TAG with --tag"
    exit 1
fi

IMAGES=(
    "${MQE_IMAGE_NAME}"
    "${DQE_IMAGE_NAME}"
    "${SAS_IMAGE_NAME}"
)

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    # Publish images

    for IMAGE_NAME in "${IMAGES[@]}"; do
        PUBLISHED_NAME=${ACR_NAME}.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}

        echo "Publishing ${IMAGE_NAME}:${IMAGE_TAG} to ${PUBLISHED_NAME}"

        docker tag ${IMAGE_NAME} ${PUBLISHED_NAME}
        docker push ${PUBLISHED_NAME}

    done

    # Publish charts

    # Workaround issues with helm authentication.
    # See https://github.com/helm/helm/issues/6214#issuecomment-694441023
    ACCESS_TOKEN=$(az acr login --name ${ACR_NAME}.azurecr.io --expose-token --output tsv --query accessToken)

    # Publish Helm charts in docker container;
    # Helm 3.7.0 was automatically installed in the
    # Azure Pipelines workers and broke publishing -
    # dockerizing this step lets us pin the Helm version.

    docker-compose \
        -f deployment/docker-compose.publish.yml \
        build

    docker-compose \
        -f deployment/docker-compose.publish.yml \
        run publish bin/publish \
        --token "${ACCESS_TOKEN}" \
        --acr "${ACR_NAME}" \
        --tag "${IMAGE_TAG}"

fi
