#!/bin/bash

set -e

echo "== Generating requirements.txt ..."
pip_compile_options="--emit-index-url --annotate --verbose"

docker compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    stac-dev \
    pip-compile ./pcstac/setup.py --extra server --extra dev -o pcstac/requirements-server.txt $pip_compile_options

docker compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    tiler-dev \
    pip-compile ./pctiler/pyproject.toml --extra server -o pctiler/requirements-server.txt $pip_compile_options

docker compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    tiler-dev \
    pip-compile ./pctiler/pyproject.toml --extra dev -o pctiler/requirements-dev.txt $pip_compile_options

docker compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    tiler-dev \
    pip-compile ./pccommon/pyproject.toml --extra server -o pccommon/requirements.txt $pip_compile_options
