#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

echo "== Generating requirements.txt ..."
pip_compile_options="--generate-hashes --reuse-hashes --emit-index-url --annotate --verbose"

docker-compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    stac-dev \
    pip-compile ./pcstac/setup.py --extra server -o pcstac/requirements-server.txt $pip_compile_options

docker-compose \
    -f docker-compose.yml \
    -f docker-compose.dev.yml \
    run --rm \
    tiler-dev \
    pip-compile ./pctiler/setup.py --extra server -o pctiler/requirements-server.txt $pip_compile_options

# docker-compose \
#     -f docker-compose.yml \
#     -f docker-compose.dev.yml \
#     run --rm \
#     sas-dev \
#     pip-compile -o pcsas/requirements.txt $pip_compile_options