#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run migrations against the development database.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    # Run database migrations
    docker-compose \
        -f docker-compose.yml \
        run --rm mqe \
        bash -c "python /opt/src/mqe/mqe/pgready.py && pypgstac migrate"

fi
