#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--dev, --db, --migrations, --deploy]
Runs tests for the project.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    docker-compose \
        -f docker-compose.yml \
        -f docker-compose.dev.yml \
        run --rm \
        tiler-dev scripts/bin/test-tiler

    docker-compose \
        -f docker-compose.yml \
        -f docker-compose.dev.yml \
        run --rm \
        stac-dev scripts/bin/test-stac

fi
