#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    if [[ "${1}" ]]; then
        echo "${1}"
    fi
    echo -n \
        "Usage: $(basename "$0") [OPTIONS]
Runs tests for the project.

Options
    --stac
        Only test pcstac
    --tiler
        Only test pctiler
    --common
        Only test pccommon
    --funcs
        Only test funcs
    --no-integration
        Don't run tests which need external authenticated resources
"
}

# Parse args
while [[ $# -gt 0 ]]; do case $1 in
    --stac)
        STAC_ONLY="1"
        shift
        ;;
    --tiler)
        TILER_ONLY="1"
        shift
        ;;
    --common)
        COMMON_ONLY="1"
        shift
        ;;
    --funcs)
        FUNCS_ONLY="1"
        shift
        ;;
    --no-integration)
        NO_INTEGRATION="--no-integration"
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        exit 1
        ;;
    esac done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    if [ -z "${TILER_ONLY}${STAC_ONLY}${FUNCS_ONLY}" ]; then

        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.dev.yml \
            run --rm \
            stac-dev scripts/bin/test-common
    fi

    if [ -z "${STAC_ONLY}${COMMON_ONLY}${FUNCS_ONLY}" ]; then
        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.dev.yml \
            run --rm \
            tiler-dev scripts/bin/test-tiler ${NO_INTEGRATION} 
    fi

    if [ -z "${TILER_ONLY}${COMMON_ONLY}${FUNCS_ONLY}" ]; then

        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.dev.yml \
            run --rm \
            stac-dev scripts/bin/test-stac
    fi

    if [ -z "${STAC_ONLY}${TILER_ONLY}${COMMON_ONLY}" ]; then

        docker-compose \
            -f docker-compose.yml \
            run --rm \
            funcs /bin/bash -c "cd /opt/src && scripts/bin/test-funcs ${NO_INTEGRATION}" 
    fi

fi
