#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") [--no-cache] [--restart]
Builds the docker containers for this project.

--no-cache: Rebuild all containers from scratch.
--restart: Restart servers and remove orphan containers
"
}

# Parse args
NO_CACHE="";
while [[ "$#" > 0 ]]; do case $1 in
    --no-cache) NO_CACHE="--no-cache"; shift;;
    --restart) RESTART_SERVERS=1; shift;;
    --help) usage; exit 0; shift;;
  *) usage "Unknown parameter passed: $1"; shift; shift;;
esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    if [ "${RESTART_SERVERS}" ]; then
        echo "==Bringing down servers.."
        docker-compose \
            -f docker-compose.yml \
            -f docker-compose.dev.yml \
            down --remove-orphans
    fi

    echo "==Building images..."
    docker-compose \
        -f docker-compose.yml \
        -f docker-compose.dev.yml \
        build ${NO_CACHE}

fi
