name: Planetary Computer APIs PR CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Run cibuild
        run: ./scripts/cibuild
        env:
          AZURITE_ACCOUNT_KEY: ${{ secrets.AZURITE_ACCOUNT_KEY }}

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.13" # stac-api-validator requires >= 3.10
          cache: "pip"

      - name: API Validator
        run: ./scripts/validate
        env:
          AZURITE_ACCOUNT_KEY: ${{ secrets.AZURITE_ACCOUNT_KEY }}
